name: stylish

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-spec:
    name: rpmlint
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: Install packages
        run: |
          dnf --setopt instal_week_deps=False install -y git-core rpmlint

      - uses: actions/checkout@v3

      - name: Run rpmlint
        run: |
          rpmlint subscription-manager.spec

  check-python:
    name: "black & flake8"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11-dev"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install packages
        run: |
          python3 -m pip install --upgrade pip wheel
          python3 -m pip install -r test-requirements.txt

      - name: Run Black
        run: |
          black . --diff

      - name: Run flake8
        run: |
          flake8 . --count --statistics
